# -*- coding: utf-8 -*-
"""FlairTester.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/15KnZynujimB_Y8K9V9I1s1FeDZXI5Kj_
"""


from flair.models import TextClassifier
from flair.data import Sentence
from pathlib import Path
import pandas as pd
import csv

def addPredictionForPositive(row):
  sentence = Sentence(row.text)
  # predict class and print
  classifier.predict(sentence)
  

  if(len(sentence.labels) == 2) :
  	if(sentence.labels[0].value == 'a'):
  		row.pred_pos = 0
  	else:
  		row.pred_pos = 1
  	if(sentence.labels[1].value == 'c'):
  		row.pred_neg = 0
  	else:
  		row.pred_neg = 1
  else:
  	val = sentence.labels[0]
  	if (val.value == 'c'):
  		row.pred_neg = 0
  		row.pred_pos = 0
  	elif (val.value == 'b'):
  		row.pred_neg = 0
  		row.pred_pos = 1
  	elif (val.value == 'a'):
  		row.pred_neg = 0
  		row.pred_pos = 0
  	elif (val.value == 'd'):
  		row.pred_neg = 1
  		row.pred_pos = 0
  	else:
  		print("incorrectVal {}".format(val))

  return row

if __name__ == "__main__":
	classifier = TextClassifier.load('./data/POLARITY_MULTI/best-model.pt')

	data_to_pred = pd.read_csv('./data/test_gold.csv',sep='\t')
	data_to_pred['pred_pos'] = 0
	data_to_pred['pred_neg'] = 0
	data_to_pred = data_to_pred.apply(lambda row: addPredictionForPositive(row), axis=1)
	data_to_pred.head()
	data_to_save = data_to_pred[['idtwitter','subj','pred_pos','pred_neg','iro','lpos','lneg','top']]
	data_to_save.idtwitter = data_to_save.idtwitter.astype(str)
	data_to_save.subj = data_to_save.subj.astype(str)
	data_to_save.pred_pos = data_to_save.pred_neg.astype(str)
	data_to_save.pred_neg = data_to_save.pred_neg.astype(str)
	data_to_save.iro = data_to_save.iro.astype(str)
	data_to_save.lpos = data_to_save.lpos.astype(str)
	data_to_save.lneg = data_to_save.lneg.astype(str)
	data_to_save.top = data_to_save.top.astype(str)
	data_to_save.to_csv(r'./data/POLARITY_MULTI/res_flair.csv',header=None,index=None, sep=',', mode='a', quotechar='"',quoting=csv.QUOTE_NONNUMERIC)